source "https://rubygems.org"

gem "actionpack", "~> 7.2.1"
gem "actionview", "~> 7.2.1"
gem "activesupport", "~> 7.2.1"
gem "actionmailer", "~> 7.2.1"
gem "activejob", "~> 7.2.1"
gem "actioncable", "~> 7.2.1"

ruby "3.3.9"

gem "puma", "~> 6.4.3"

# MongoDB gems
gem "mongoid", "~> 8.0"
gem "mongo", "~> 2.18"

# JWT gem
gem "jwt"


gem "bcrypt", "~> 3.1.7"


gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "rack-cors"
gem "importmap-rails"

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

group :development, :test do
  
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", "~> 7.0.0", require: false

  gem "rubocop-rails-omakase", require: false

  gem "dotenv-rails", groups: [:development, :test]

  gem "benchmark", require: false

  gem "ostruct", require: false
end