services:
  - type: web
    name: green-rails-travel-planner
    env: ruby
    repo: https://github.com/jashjpatel/GreenTravelPlanner
    buildCommand: bundle config set --local deployment true && bundle install --without development test
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: "1"